-- MySQL Script generated by MySQL Workbench
-- jue 25 jul 2019 13:50:06 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema youtubemd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema youtubemd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS  "youtubemd"  ;
-- SHOW WARNINGS;
-- USE "youtubemd" ;
--
-- -----------------------------------------------------
-- Table "youtubemd"."DownloadInformation"
-- -----------------------------------------------------
CREATE TABLE  "youtubemd"."DownloadInformation" (
  "file_id" VARCHAR(50) NOT NULL,
  "audioQuality" ENUM('320k', '256k', '128k') NOT NULL,
  "audioSampling" ENUM('44000', '48000') NULL,
  "Metadata_idMetadata" INT NOT NULL,
  "VideoInformation_id" VARCHAR(11) NOT NULL,
  PRIMARY KEY ("file_id", "Metadata_idMetadata", "VideoInformation_id"),
  CONSTRAINT "fk_DownloadInformation_Metadata1"
    FOREIGN KEY ("Metadata_idMetadata")
    REFERENCES "youtubemd"."Metadata" ("idMetadata")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_DownloadInformation_VideoInformation1"
    FOREIGN KEY ("VideoInformation_id")
    REFERENCES "youtubemd"."VideoInformation" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
CHECKSUM = 1;

-- SHOW WARNINGS;
--
-- SHOW WARNINGS;
--
-- SHOW WARNINGS;
--
-- SHOW WARNINGS;

-- -----------------------------------------------------
-- Table "youtubemd"."DownloadStatistics"
-- -----------------------------------------------------
CREATE TABLE  "youtubemd"."DownloadStatistics" (
  "timesRequested" INT NOT NULL DEFAULT 0,
  "DownloadInformation_file_id" VARCHAR(50) NOT NULL,
  PRIMARY KEY ("DownloadInformation_file_id"),
  CONSTRAINT "fk_DownloadStatistics_DownloadInformation1"
    FOREIGN KEY ("DownloadInformation_file_id")
    REFERENCES "youtubemd"."DownloadInformation" ("file_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
CHECKSUM = 1;

-- SHOW WARNINGS;

-- -----------------------------------------------------
-- Table "youtubemd"."History"
-- -----------------------------------------------------
CREATE TABLE  "youtubemd"."History" (
  "User_id" INT NOT NULL,
  "DownloadInformation_file_id" VARCHAR(50) NOT NULL,
  PRIMARY KEY ("User_id", "DownloadInformation_file_id"),
  CONSTRAINT "fk_History_User1"
    FOREIGN KEY ("User_id")
    REFERENCES "youtubemd"."User" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_History_DownloadInformation1"
    FOREIGN KEY ("DownloadInformation_file_id")
    REFERENCES "youtubemd"."DownloadInformation" ("file_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
CHECKSUM = 1;

-- SHOW WARNINGS;
--
-- SHOW WARNINGS;

-- -----------------------------------------------------
-- Table "youtubemd"."Metadata"
-- -----------------------------------------------------
CREATE TABLE  "youtubemd"."Metadata" (
  "idMetadata" INT NOT NULL ,
  "title" VARCHAR(100) NOT NULL,
  "artist" VARCHAR(60) NOT NULL,
  "cover" BLOB NOT NULL,
  "duration" INT NULL,
  "customMetadata" TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY ("idMetadata"));
CHECKSUM = 1;

-- SHOW WARNINGS;

-- -----------------------------------------------------
-- Table "youtubemd"."Playlist"
-- -----------------------------------------------------
CREATE TABLE  "youtubemd"."Playlist" (
  "id" VARCHAR(60) NOT NULL,
  PRIMARY KEY ("id"));
CHECKSUM = 1;

-- SHOW WARNINGS;
--
-- SHOW WARNINGS;

-- -----------------------------------------------------
-- Table "youtubemd"."Playlist_has_VideoInformation"
-- -----------------------------------------------------
CREATE TABLE  "youtubemd"."Playlist_has_VideoInformation" (
  "Playlist_id" VARCHAR(60) NOT NULL,
  "VideoInformation_id" VARCHAR(11) NOT NULL,
  PRIMARY KEY ("Playlist_id", "VideoInformation_id"),
  CONSTRAINT "fk_Playlist_has_VideoInformation_Playlist1"
    FOREIGN KEY ("Playlist_id")
    REFERENCES "youtubemd"."Playlist" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_Playlist_has_VideoInformation_VideoInformation1"
    FOREIGN KEY ("VideoInformation_id")
    REFERENCES "youtubemd"."VideoInformation" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
CHECKSUM = 1;

-- SHOW WARNINGS;
--
-- SHOW WARNINGS;
--
-- SHOW WARNINGS;

-- -----------------------------------------------------
-- Table "youtubemd"."PlaylistStatistics"
-- -----------------------------------------------------
CREATE TABLE  "youtubemd"."PlaylistStatistics" (
  "timesRequested" INT NOT NULL,
  "Playlist_id" VARCHAR(60) NOT NULL,
  PRIMARY KEY ("Playlist_id"),
  CONSTRAINT "fk_PlaylistStatistics_Playlist1"
    FOREIGN KEY ("Playlist_id")
    REFERENCES "youtubemd"."Playlist" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
CHECKSUM = 1;

-- SHOW WARNINGS;

-- -----------------------------------------------------
-- Table "youtubemd"."Preferences"
-- -----------------------------------------------------
CREATE TABLE  "youtubemd"."Preferences" (
  "language" VARCHAR(3) NOT NULL DEFAULT 'en',
  "audioQuality" ENUM('320k', '256k', '128k') NOT NULL DEFAULT '128k',
  "audioSampling" ENUM('44000', '48000') NOT NULL DEFAULT '44000',
  "sendSongLinks" TINYINT NOT NULL DEFAULT 0,
  "askForMetadata" TINYINT NOT NULL DEFAULT 1,
  "User_id" INT NOT NULL,
  PRIMARY KEY ("User_id"),
  CONSTRAINT "fk_Preferences_User"
    FOREIGN KEY ("User_id")
    REFERENCES "youtubemd"."User" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
CHECKSUM = 1;

-- SHOW WARNINGS;

-- -----------------------------------------------------
-- Table "youtubemd"."User"
-- -----------------------------------------------------
CREATE TABLE  "youtubemd"."User" (
  "id" INT NOT NULL DEFAULT 0,
  "name" VARCHAR(45) NULL DEFAULT 'User',
  "surname" VARCHAR(45) NULL,
  "username" VARCHAR(45) NULL,
  "lastSeen" TIMESTAMP NOT NULL,
  "firstUsage" TIMESTAMP NOT NULL,
  PRIMARY KEY ("id"));
CHECKSUM = 1

-- SHOW WARNINGS;
--
-- SHOW WARNINGS;
--
-- SHOW WARNINGS;

-- -----------------------------------------------------
-- Table "youtubemd"."VideoInformation"
-- -----------------------------------------------------
CREATE TABLE  "youtubemd"."VideoInformation" (
  "id" VARCHAR(11) NOT NULL,
  "title" VARCHAR(100) NOT NULL,
  "channel" VARCHAR(60) NOT NULL,
  PRIMARY KEY ("id"));
CHECKSUM = 1;

-- SHOW WARNINGS;
--
-- SHOW WARNINGS;

-- -----------------------------------------------------
-- Table "youtubemd"."VideoStatistics"
-- -----------------------------------------------------
CREATE TABLE  "youtubemd"."VideoStatistics" (
  "timesRequested" INT NOT NULL DEFAULT 0,
  "VideoInformation_id" VARCHAR(11) NOT NULL,
  PRIMARY KEY ("VideoInformation_id"),
  CONSTRAINT "fk_VideoStatistics_VideoInformation1"
    FOREIGN KEY ("VideoInformation_id")
    REFERENCES "youtubemd"."VideoInformation" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
CHECKSUM = 1;

-- SHOW WARNINGS;
-- 
-- SET SQL_MODE=@OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
DROP SEQUENCE IF EXISTS "youtubemd"."Metadata_idMetadata_sequence";
CREATE SEQUENCE  "youtubemd"."Metadata_idMetadata_sequence";
ALTER TABLE "youtubemd"."Metadata" ALTER COLUMN "idMetadata" SET DEFAULT NEXTVAL('"youtubemd"."Metadata_idMetadata_sequence"');
DROP SEQUENCE IF EXISTS "youtubemd"."Metadata__sequence";
CREATE SEQUENCE  "youtubemd"."Metadata__sequence";
ALTER TABLE "youtubemd"."Metadata" ALTER COLUMN "" SET DEFAULT NEXTVAL('"youtubemd"."Metadata__sequence"');
